# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 60984e3f3625b1779a568d2fcff7027e29bf2a9bc2228c0e3de9f62f83738309c08475987edcac7f2bcaf0faab208ffe3198a128535cdc5f8b116826027e521f

test:
  secret_key_base: b4bcef192f71cba3a15ee1b6bc820b877977b22d1e1ad37aa79116646ba4639d04392759b34048fbdb16ebd53d2b8f8099d237aa37d246a6bfb4572a37506f42

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
